"""Add is_paid to subscriptions

Revision ID: 911370570968
Revises: 5a18e06eb236
Create Date: 2026-04-26 02:55:34.757215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '911370570968'
down_revision = '5a18e06eb236'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_paid', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_column('is_paid')

    # ### end Alembic commands ###
